### ISSUE TITLE
NPM publish rights to plotly.js team members?

### ISSUE THREAD

**Issue by etpinard** [gl-vis/regl-error2d#3]
Hi @dy, would you mind giving me publish rights to https://www.npmjs.com/package/regl-error2d ?

I believe this is the last remaining `regl-*` package that the npm plotly org can't publish to.

Thank you very much. I hope things are going well for you!

**Comment by dy** [comment]
Sure @etpinard. Done!

**Comment by dy** [comment]
Added @archmoj as well.

**Comment by etpinard** [comment]
@dy is the man!
